// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDveiwj014YnwT5R5vwLvcMDkE3mDfzdhE',
    appId: '1:230123407289:android:231fa1cad9aa55961b5868',
    messagingSenderId: '230123407289',
    projectId: 'chat-job-2',
    storageBucket: 'chat-job-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDveiwj014YnwT5R5vwLvcMDkE3mDfzdhE',
    appId: '1:230123407289:ios:231fa1cad9aa55961b5868', // Placeholder - update with actual iOS app ID from Firebase console
    messagingSenderId: '230123407289',
    projectId: 'chat-job-2',
    storageBucket: 'chat-job-2.firebasestorage.app',
    iosBundleId: 'co.andelwood2.chat_job', // Assuming same as Android package name
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveiwj014YnwT5R5vwLvcMDkE3mDfzdhE',
    appId: '1:230123407289:web:231fa1cad9aa55961b5868', // Placeholder - add web app in Firebase console and update
    messagingSenderId: '230123407289',
    projectId: 'chat-job-2',
    storageBucket: 'chat-job-2.firebasestorage.app',
    authDomain: 'chat-job-2.firebaseapp.com',
    measurementId: 'G-XXXXXXXXXX', // Placeholder - update with actual measurement ID if using Analytics
  );
}